# CNB 构建配置
# 构建 Docker 镜像并推送到腾讯云镜像仓库

main:
  push:
    - services:
        - docker
      env:
        TCR_REGISTRY: xiongfei-test.tencentcloudcr.com
        TCR_USERNAME: "100013033031"
        IMAGE_NAME: xiongfei-test.tencentcloudcr.com/xiongfei/mps-for-manju
        IMAGE_TAG: v0501
      stages:
        - name: 登录腾讯云镜像仓库
          script: |
            echo 'eyJhbGciOiJSUzI1NiIsImtpZCI6Iks1RVc6NVFUUDpDSVhaOkdVWkY6UzNFQjpHTlVPOjMzWVU6TlhXUzpJVkI3OldLV006U0dTUTpISTNSIn0.eyJvd25lclVpbiI6IjEwMDAxODAyMTkzMiIsIm9wZXJhdG9yVWluIjoiMTAwMDEzMDMzMDMxIiwiZXhwIjoxNzc3NTc1NTE1LCJuYmYiOjE3Nzc1NzE5MTUsImlhdCI6MTc3NzU3MTkxNX0.ZRxlaFvpZzTu47m_bxhLmUpfNWeG6odEMYp2ldoHoVsxAT_DT-RtyYHCgfCXJAeCzmjaK_Vi8OXmdXCtaOhN_WB55zOHS12_lxCydLKvJIOu0qyb7pEQk223LAXhOv1nxXSTVRlRi6YRXDJqcir-GP9DGSL1_4aeyB4w3NCFCUPg3_H19rLOXr2Qh2YOB6MYPszheWPbJLY3wjEEF7O9QWbG9CV1fpQvLMSHkCgChclFNwVanKLoWWTPXclf2LMxE-E-OuOVDAqPaO8-kqWQH8ipxfTP4ZLgMdLtnHphs4cjQsUd9VlOKYCTGosbvV4nwrAtf0FW4Te7KGP8L523tQ' | docker login -u $TCR_USERNAME --password-stdin $TCR_REGISTRY
        - name: 构建 Docker 镜像
          script: |
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - name: 推送镜像到腾讯云镜像仓库
          script: |
            docker push $IMAGE_NAME:$IMAGE_TAG
